---

title: "Server assertion  loading large amount of data"
layout: issue
tags: 
permalink: /browse/CDV-631

issue_key: CDV-631
issue_numeric_sort_key: 631
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Closed"
resolution: "Fixed"
priority: "1 Critical"
components: "DSO:L2"
labels: 
assignee: "hhuynh"
reporter: "foshea"
votes:  0
watchers: 0

created: "2008-02-28T13:45:56.000-0500"
updated: "2008-05-29T12:29:42.000-0400"
resolved: "2008-03-03T04:31:35.000-0500"




---

{% raw %}

## Description

<div markdown="1" class="description">

Assertion Error during load test
 008-01-31 19:19:19,953 [WorkerThread(managed\_object\_fault\_stage,2)] ERROR com.tc.server.TCServerMain - Thread:Thread[WorkerThread(managed\_object\_fault\_stage,2),5,TC Thread Group] got an uncaught exception. About to sleep then exit.
com.tc.util.TCAssertionError: object was not null
at com.tc.util.Assert.failure(Assert.java:60)
at com.tc.util.Assert.assertNull(Assert.java:139)
at com.tc.util.Assert.assertNull(Assert.java:129)
at com.tc.objectserver.impl.ObjectManagerImpl.addNewReference(ObjectManagerImpl.java:326)
at com.tc.objectserver.impl.ObjectManagerImpl.addNewReference(ObjectManagerImpl.java:322)
at com.tc.objectserver.impl.ObjectManagerImpl.createObject(ObjectManagerImpl.java:653)
at com.tc.objectserver.impl.ObjectManagerImpl.createNewObjectsAndAddTo(ObjectManagerImpl.java:429)
at com.tc.objectserver.impl.ObjectManagerImpl.basicLookupObjectsFor(ObjectManagerImpl.java:414)
at com.tc.objectserver.impl.ObjectManagerImpl.processPendingLookups(ObjectManagerImpl.java:738)
at com.tc.objectserver.impl.ObjectManagerImpl.postRelease(ObjectManagerImpl.java:546)
at com.tc.objectserver.impl.ObjectManagerImpl.addFaultedObject(ObjectManagerImpl.java:315)
at com.tc.objectserver.handler.ManagedObjectFaultHandler.handleEvent(ManagedObjectFaultHandler.java:34)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:142)
2008-01-31 19:19:20,047 [WorkerThread(managed\_object\_fault\_stage,1)] ERROR com.tc.server.TCServerMain - Thread:Thread[WorkerThread(managed\_object\_fault\_stage,1),5,TC Thread Group] got an uncaught exception. About to sleep then exit.
java.lang.AssertionError: ManagedObjectReference is not what was expected : ManagedObjectImpl
    +--> identityHashCode: 1754009265
    +--> id: ObjectID=[30538107]
    +--> className: UNKNOWN
    +--> version:-1
    +--> state: null
    +--> isDirty:true +--> isNew:true +--> isReferenced:false
    +--> next: false prev: false oid : ObjectID=[30538107]
at com.tc.objectserver.impl.ObjectManagerImpl.addFaultedObject(ObjectManagerImpl.java:300)
at com.tc.objectserver.handler.ManagedObjectFaultHandler.handleEvent(ManagedObjectFaultHandler.java:34)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:142)
2008-01-31 19:19:22,972 [CommonShutDownHook - com.tc.object.msg.RequestManagedObjectResponseMessage$1@5bb0ce4] INFO com.tc.net.protocol.TCNetworkMessage - No of times Buffers wasted = 0 Buffers wasted count = 0


</div>

## Comments


{:.comment-heading}
### **Fiona OShea** <span class="date">2008-02-28</span>

<div markdown="1" class="comment">

Creating dup of DEV-1283 to track for external users.  forum poster also saw this issue http://forums.terracotta.org/forums/posts/list/826.page#4983

</div>


{:.comment-heading}
### **Saravanan Subbiah** <span class="date">2008-03-03</span>

<div markdown="1" class="comment">

Fixed in trunk. Should be available in latest nightlys and 2.6 release.

</div>



{% endraw %}
