---

title: "from the forums - AssertionError in L2 "
layout: issue
tags: 
permalink: /browse/CDV-358

issue_key: CDV-358
issue_numeric_sort_key: 358
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Closed"
resolution: "Cannot Reproduce"
priority: "1 Critical"
components: ""
labels: 
assignee: "ssubbiah"
reporter: "foshea"
votes:  0
watchers: 0

created: "2007-08-01T19:20:48.000-0400"
updated: "2012-07-27T19:59:27.000-0400"
resolved: "2007-08-15T21:19:36.000-0400"

---



{% raw %}



## Description

<div markdown="1" class="description">

http://forums.terracotta.org/forums/posts/list/357.page

2007-07-31 22:13:18,765 INFO - Terracotta Server has started up as ACTIVE node on port 9510 successfully, and is now ready for work.
 Exception in thread "WorkerThread(managed\_object\_fault\_stage,1)" java.lang.AssertionError: Request for a non-existent object: ObjectID=[121033]
 	at com.tc.objectserver.impl.ObjectManagerImpl.getOrLookupReference(ObjectManagerImpl.java:299)
 	at com.tc.objectserver.impl.ObjectManagerImpl.basicLookupObjectsFor(ObjectManagerImpl.java:433)
 	at com.tc.objectserver.impl.ObjectManagerImpl.processPendingLookups(ObjectManagerImpl.java:777)
 	at com.tc.objectserver.impl.ObjectManagerImpl.postRelease(ObjectManagerImpl.java:576)
 	at com.tc.objectserver.impl.ObjectManagerImpl.addFaultedObject(ObjectManagerImpl.java:351)
 	at com.tc.objectserver.handler.ManagedObjectFaultHandler.handleEvent(ManagedObjectFaultHandler.java:34)
 	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:140)
 java.lang.AssertionError: Request for a non-existent object: ObjectID=[121033]
 	at com.tc.objectserver.impl.ObjectManagerImpl.getOrLookupReference(ObjectManagerImpl.java:299)
 	at com.tc.objectserver.impl.ObjectManagerImpl.basicLookupObjectsFor(ObjectManagerImpl.java:433)
 	at com.tc.objectserver.impl.ObjectManagerImpl.processPendingLookups(ObjectManagerImpl.java:777)
 	at com.tc.objectserver.impl.ObjectManagerImpl.postRelease(ObjectManagerImpl.java:576)
 	at com.tc.objectserver.impl.ObjectManagerImpl.addFaultedObject(ObjectManagerImpl.java:351)
 	at com.tc.objectserver.handler.ManagedObjectFaultHandler.handleEvent(ManagedObjectFaultHandler.java:34)
 	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:140)
 

</div>

## Comments


{:.comment-heading}
### **Fiona OShea** <span class="date">2007-08-15</span>

<div markdown="1" class="comment">

Is this the same issues as DEV-838 and DEV-822? thanks

</div>


{:.comment-heading}
### **Saravanan Subbiah** <span class="date">2007-08-15</span>

<div markdown="1" class="comment">

He was actually not using DMI but he doesnt have the bandwidth to test it with the latest 2.4.1

We have fixed a couple of issues in 2.4.1 with exact symptoms and since we dont have the app inhouse, there is no way to verify which is unfortunate. I am closing this until someone comes back to us with the same problem with 2.4.1 or later release.

</div>



{% endraw %}
