---

title: "exceptions during hydate fail to clear the \"lookup in progress\" flag in ClientObjectManagerImpl.lookup(ObjectID id, ObjectID parentContext, boolean noDepth)"
layout: issue
tags: 
permalink: /browse/CDV-591

issue_key: CDV-591
issue_numeric_sort_key: 591
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Closed"
resolution: "Fixed"
priority: "2 Major"
components: ""
labels: 
assignee: "hhuynh"
reporter: "teck"
votes:  0
watchers: 0

created: "2008-01-23T16:35:12.000-0500"
updated: "2008-05-16T16:25:20.000-0400"
resolved: "2008-04-27T04:40:37.000-0400"

---



{% raw %}


## Attachments
  
* <em>teck</em> (15.000 k, application/x-gzip) [CDV-591.tar.gz](/attachments/CDV/CDV-591/CDV-591.tar.gz)
  



## Description

<div markdown="1" class="description">

An example of an exception occurring is here CDV-590. The side effect is that basicAddLocal() is never called which is where we call markObjectLookupNotInProgress(). 

It seems that we should be clearing that flag even though we are returning an exception to the application. Without clearing the lookup flag, any other threads that come in to lookup the same object will just hang indefinitely since it appears that a lookup is already in progress -- the stack would be like this (for 2.5.0):

"http-80-Processor15" daemon prio=1 tid=0x08d53800 nid=0x7f84 in Object.wait() [0x742fb000..0x742fcfc0]
	at java.lang.Object.wait(Native Method)
	- waiting on <0x826866e0> (a com.tc.object.ClientObjectManagerImpl)
	at java.lang.Object.wait(Object.java:474)
	at com.tc.object.ClientObjectManagerImpl.lookup(ClientObjectManagerImpl.java:502)
	- locked <0x826866e0> (a com.tc.object.ClientObjectManagerImpl)
	at com.tc.object.ClientObjectManagerImpl.lookupObject(ClientObjectManagerImpl.java:418)
	at com.tc.object.ClientObjectManagerImpl.lookupObject(ClientObjectManagerImpl.java:407)
	at com.tc.object.TCObjectPhysical.resolveReference(TCObjectPhysical.java:133)


</div>

## Comments



{% endraw %}
