---

title: "BlockingCache.get() Blocks When A RuntimeException is Thrown"
layout: issue
tags: 
permalink: /browse/EHC-197

issue_key: EHC-197
issue_numeric_sort_key: 197
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: ""
components: ""
labels: 
assignee: "drb"
reporter: "sourceforgetracker"
votes:  0
watchers: 0

created: "2009-09-21T15:07:52.000-0400"
updated: "2009-09-22T23:44:36.000-0400"
resolved: "2009-09-22T23:44:36.000-0400"

---



{% raw %}



## Description

<div markdown="1" class="description">

For the method 

public Element get(final Object key) throws LockTimeoutException {

This call gets the underlying object, and Blocks if a null element is returned.

            final Element element = cache.get(key);
            if (element != null) {
                //ok let the other threads in
                lock.release();
                return element;
            } else {
                //don't release the read lock until we put
                return null;
            }

If a RuntimeException is thrown with "cache.get()", then the BlockingCache will be left in a blocking state. 

In my experience, an IOException was thrown in cache.get() and wrapped as a RuntimeException by the SpringJdbcStore. 

Perhaps the documentation can be changed to help warn other developers who may run into the same problem.

"Note. If a LockTimeoutException or RuntimeException is thrown while doing a {@link #get} it means the lock was never acquired,"

Sourceforge Ticket ID: 1990091 - Opened By: nobody - 10 Jun 2008 19:16 UTC

</div>

## Comments


{:.comment-heading}
### **Sourceforge Tracker** <span class="date">2009-09-21</span>

<div markdown="1" class="comment">

Logged In: YES 
user\1id=693320
Originator: NO

Hi

Sorry you got caught by that. I think it is a documentation issue. I have changed the javadoc as follows:

/\1\1
     \1 Looks up an entry.  Blocks if the entry is null until a call to {@link #put} is done
     \1 to put an Element in.
     \1 <p/>
     \1 If a put is not done, the lock is never released.
     \1 <p/>
     \1 If this method throws an exception, it is the responsibility of the caller to catch that exception and call 
     \1 <code>put(new Element(key, null));</code> to release the lock acquired. See {@link net.sf.ehcache.constructs.blocking.SelfPopulatingCache}
     \1 for an example.
     \1 
     \1 Note. If a LockTimeoutException is thrown while doing a {@link #get} it means the lock was never acquired,
     \1 therefore it is a threading error to call {@link #put}
     \1
     \1 @throws LockTimeoutException if timeout millis is non zero and this method has been unable to
     \1                              acquire a lock in that time
     \1 @throws RuntimeException if thrown the lock will not released. Catch and call<code>put(new Element(key, null));</code> 
     \1 to release the lock acquired.    
     \1/

That should alert developers accordingly as to the contract.

Thanks for pointing this out.

The fix is in trunk and will be in ehcache-1.5.0 which will be out this weekend.

Greg
Comment by: gregluck - 9 Jul 2008 07:29 UTC

</div>


{:.comment-heading}
### **Fiona OShea** <span class="date">2009-09-22</span>

<div markdown="1" class="comment">

Re-opening so that I can properly close out these issues and have correct Resolution status in Jira

</div>



{% endraw %}
