---

title: "Chaining CacheException"
layout: issue
tags: 
permalink: /browse/EHC-256

issue_key: EHC-256
issue_numeric_sort_key: 256
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: ""
components: ""
labels: 
assignee: "drb"
reporter: "sourceforgetracker"
votes:  0
watchers: 0

created: "2009-09-21T15:07:58.000-0400"
updated: "2009-09-22T23:44:39.000-0400"
resolved: "2009-09-22T23:44:39.000-0400"




---

{% raw %}

## Description

<div markdown="1" class="description">

1) CacheException is not chained for JDK1.3 or lower.
- could implement custom chaining feature

2) CacheException should accept caused exception when
rethrown exceptions
- add Throwable constructor

This will easy bug hunting as the original stacktrace
is avail.

/Claus
Sourceforge Ticket ID: 1026314 - Opened By: nobody - 11 Sep 2004 13:10 UTC

</div>

## Comments


{:.comment-heading}
### **Sourceforge Tracker** <span class="date">2009-09-21</span>

<div markdown="1" class="comment">

Logged In: YES 
user\_id=693320

Claus

I have gone for option 2. There is a initialCause field and accessor to get the 
exception cause. Have changed the exception throwing code to populate the 
field.

Thanks for the suggestion. It is in trunk and will be in ehcache-1.2

Regards
Greg Luck
Comment by: gregluck - 15 Apr 2006 06:03 UTC

</div>


{:.comment-heading}
### **Fiona OShea** <span class="date">2009-09-22</span>

<div markdown="1" class="comment">

Re-opening so that I can properly close out these issues and have correct Resolution status in Jira

</div>



{% endraw %}
