---

title: "Wrap original exceptions during configuration"
layout: issue
tags: 
permalink: /browse/EHC-276

issue_key: EHC-276
issue_numeric_sort_key: 276
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: ""
components: ""
labels: 
assignee: "drb"
reporter: "sourceforgetracker"
votes:  0
watchers: 0

created: "2009-09-21T15:07:59.000-0400"
updated: "2009-09-22T23:44:41.000-0400"
resolved: "2009-09-22T23:44:41.000-0400"

---



{% raw %}



## Description

<div markdown="1" class="description">

I've been trying to run Hibernate through JNLP, and was
getting an exception from ehcache indicating a problem
with the failsafe configuration file:

org.hibernate.cache.CacheException:
net.sf.ehcache.CacheException: Error configuring from
jar:file:ehcache-1.2beta5.jar!/ehcache-failsafe.xml
Error was null:12: Could not set attribute "path".

I looked into the ConfigurationFactory code (based on
the call stack) and saw that the parseConfiguration
method was ignoring the original exception and throwing
a CacheException.  So I had no idea what the original
exception was - I had to modify the code and add extra
debugging to figure out the root cause.

(Turns out it was an unsigned xerces jar in my classpath).

The attached mods to ConfigurationFactory set the
initCause of the thrown CacheException to provide more
debugging help.

Sourceforge Ticket ID: 1458049 - Opened By: nobody - 24 Mar 2006 22:25 UTC

</div>

## Comments


{:.comment-heading}
### **Fiona OShea** <span class="date">2009-09-22</span>

<div markdown="1" class="comment">

Re-opening so that I can properly close out these issues and have correct Resolution status in Jira

</div>



{% endraw %}
