---

title: "WriteBehindQueue implementation doesn't handle exceptions in CacheWriters gracefully"
layout: issue
tags: 
permalink: /browse/EHC-750

issue_key: EHC-750
issue_numeric_sort_key: 750
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: "2 Major"
components: "ehcache"
labels: 
assignee: ""
reporter: "gbevin"
votes:  0
watchers: 0

created: "2010-07-12T05:26:40.000-0400"
updated: "2012-07-27T19:59:50.000-0400"
resolved: "2010-10-12T02:19:15.000-0400"




---

{% raw %}

## Description

<div markdown="1" class="description">

The non-clustered WriteBehindQueue implementation calls 'processItems()' in its ProcessingThread without catching the exceptions that might be thrown during that method call.

In the clustered async implementation inside the Terracotta Toolkit this is implemented as such;


```
  try {
    processItems();
  } catch (final Throwable e) {
    errorHandler.onError(ProcessingBucket.this, e);
    continue;
  }
```


This works since there's a concept of error handlers that isn't present in the non-clustered write behind implementation in Ehcache core. The default error handler simply logs the exceptions that occurred.

Should we implement a logging-only version for Ehcache Core or also introduce error handlers?


For the time being, users can work around this by handling the CacheExceptions themselves in their CacheWriter implementations.

</div>

## Comments


{:.comment-heading}
### **gluck** <span class="date">2010-10-12</span>

<div markdown="1" class="comment">

Added to documentation which I think is the most appropriate action right now.

</div>



{% endraw %}
